---
# This AWS CloudFormation template
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This example template demonstrates creating an Auto Scaling group with a specified
  number of EC2 instances with UserData that initializes the instances. In this case, 
  the UserData calls the cfn-init.exe command, which uses the default configSet to initialize
  the instances.

Parameters:
  pApplicationName:
    Description: The name of the application
    Type: String

  pInstanceRole:
    Description: The ARN for the AWS IAM role that has read access to the archive file key specified
    Type: String
    # AllowedPattern: "arn:aws:iam::[0-9]{12}:role/.+"
    AllowedPattern: "[a-zA-Z]+"
    ConstraintDescription: Value must be a valid IAM ARN (Amazon Resource Name)

  pSshKeyName:
    Description: The SSH key to use to access the machine
    Type: AWS::EC2::KeyPair::KeyName
    
  pMinInstances:
    Description: The minimum number of instances in the Auto Scaling group
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 25

  pMaxInstances:
    Description: The maximum number of instances in the Auto Scaling group
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 25

  pInstanceSize:
    Description: The size of the EC2 instance
    Default: t3.medium
    Type: String
    AllowedValues:
    - t3.nano
    - t3.micro
    - t3.medium
    
  pIncomingPort:
    Description: The incoming port to expose in the security group
    Type: String
    Default: 8080

Resources:

  AppServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        - pApplicationName: !Ref pApplicationName
        - pInstanceRole: !Ref pInstanceRole
        - pSshKeyName: !Ref pSshKeyName
        - pMinInstances: !Ref pMinInstances
        - pMaxInstances: !Ref pMaxInstances
        - pInstanceSize: !Ref pInstanceSize
        - pIncomingPort: !Ref pIncomingPort
      TemplateURL: example-windows-ec2.yml
      TimeoutInMinutes: 15

  DataServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        - pApplicationName: !Ref pApplicationName
        - pInstanceRole: !Ref pInstanceRole
        - pSshKeyName: !Ref pSshKeyName
        - pMinInstances: !Ref pMinInstances
        - pMaxInstances: !Ref pMaxInstances
        - pInstanceSize: !Ref pInstanceSize
        - pIncomingPort: !Ref pIncomingPort
      TemplateURL: example-windows-ec2.yml
      TimeoutInMinutes: 15

  WebServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        - pApplicationName: !Ref pApplicationName
        - pInstanceRole: !Ref pInstanceRole
        - pSshKeyName: !Ref pSshKeyName
        - pMinInstances: !Ref pMinInstances
        - pMaxInstances: !Ref pMaxInstances
        - pInstanceSize: !Ref pInstanceSize
        - pIncomingPort: !Ref pIncomingPort
      TemplateURL: example-windows-ec2.yml
      TimeoutInMinutes: 15